<a href="https://colab.research.google.com/github/BYRic-F/Data_practice/blob/main/Entrainement_OPmobility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

# 1. Création du jeu de données (Ne pas modifier)
data = {
    'sim_id': range(1, 11),
    'temp_input': [200, 210, 190, 220, 205, 180, 230, 210, 195, 200],
    'pressure_bar': [5.1, 4.9, 5.0, 5.5, 4.8, 3.5, 6.0, 5.2, 5.0, 4.9],
    'status': ['Success', 'Success', 'Failed', 'Success', 'Success', 'Failed', 'Success', 'Success', 'Success', 'Success'],
    'max_thinning_mm': [1.2, 1.1, np.nan, 0.9, 1.3, np.nan, 0.8, 1.1, 1.2, 1.1]
}
df = pd.DataFrame(data)

# --- TON TRAVAIL ---
# Question A : Supprime les lignes où la simulation a 'Failed'.
# Question B : Calcule la moyenne de 'temp_input' uniquement pour les simulations réussies.
# Question C : Crée une nouvelle colonne 'is_critical' qui vaut True si 'max_thinning_mm' < 1.0.

In [24]:
df.dtypes

,0
sim_id,int64
temp_input,int64
pressure_bar,float64
status,object
max_thinning_mm,float64


In [8]:
df.head(5)

,sim_id,temp_input,pressure_bar,status,max_thinning_mm
0,1,200,5.1,Success,1.2
1,2,210,4.9,Success,1.1
2,3,190,5.0,Failed,NaN
3,4,220,5.5,Success,0.9
4,5,205,4.8,Success,1.3


In [12]:
#Question A : Supprime les lignes où la simulation a 'Failed'
df_clean = df[df['status'] == "Success"].reset_index().copy()
df_clean.head(5)

,index,sim_id,temp_input,pressure_bar,status,max_thinning_mm
0,0,1,200,5.1,Success,1.2
1,1,2,210,4.9,Success,1.1
2,3,4,220,5.5,Success,0.9
3,4,5,205,4.8,Success,1.3
4,6,7,230,6.0,Success,0.8


In [13]:
# Question B : Calcule la moyenne de 'temp_input' uniquement pour les simulations réussies.
mean = df_clean["temp_input"].mean()
print(f"durée moyenne = {mean}")

durée moyenne = 208.75


In [25]:
# Question C : Crée une nouvelle colonne 'is_critical' qui vaut True si 'max_thinning_mm' < 1.0.

df_clean['is_critical'] = df_clean['max_thinning_mm'] < 1

In [26]:
df_clean.head(5)

,index,sim_id,temp_input,pressure_bar,status,max_thinning_mm,is_critical
0,0,1,200,5.1,Success,1.2,False
1,1,2,210,4.9,Success,1.1,False
2,3,4,220,5.5,Success,0.9,True
3,4,5,205,4.8,Success,1.3,False
4,6,7,230,6.0,Success,0.8,True


Exercice  2

Imagine que tu as ce tableau NumPy mesh_data (1000 points, 4 colonnes : x, y, z, epaisseur).

In [27]:
import numpy as np

# Création du maillage fictif
np.random.seed(42)
mesh_data = np.random.rand(1000, 4)
mesh_data[:, 3] = np.random.uniform(0.5, 3.0, 1000) # Épaisseur en mm

1. Isoler uniquement la colonne des épaisseurs dans une variable epaisseurs.

2. Trouver la valeur de l'épaisseur la plus faible (le point le plus critique).

3. (Optionnel) Trouver les coordonnées (x, y, z) de ce point précis.

In [28]:
mesh_data

array([[0.37454012, 0.95071431, 0.73199394, 1.9299897 ],
       [0.15601864, 0.15599452, 0.05808361, 2.51358082],
       [0.60111501, 0.70807258, 0.02058449, 2.40040232],
       ...,
       [0.33745428, 0.87068846, 0.08352491, 1.31960709],
       [0.75246834, 0.05129385, 0.49253538, 2.53936345],
       [0.33440118, 0.39457232, 0.52994059, 1.99328095]])

In [31]:
epaisseur = mesh_data[:, 3]

print(f"L'epaisseur la plus faible est {epaisseur.min()}")

L'epaisseur la plus faible est 0.5000767971134561


In [40]:
index_min = np.argmin(epaisseur)
coords_min = mesh_data[index_min, :]
coords_min = coords_min[:3]
print(coords_min)

[0.12063587 0.46077877 0.20633372]


In [ ]:
# Maintenant que tu as coords_min (qui est un petit tableau avec [x, y, z]),
# comment calculerais-tu sa distance par rapport à l'origine (0, 0, 0) ?

In [47]:
distance = np.linalg.norm(coords_min)

print(distance)

0.5190796565240426


Exercice 3 : la Normalisation (Min-Max Scaling).

In [48]:
temps = np.array([180, 200, 220, 190, 210])

La mission : Écris la ligne de code (en une seule fois si possible) pour transformer ce tableau afin que les valeurs soient comprises entre 0 et 1.

In [51]:
def normalisation(x):
  x_norm = (x-np.min(x))/(np.max(x) - np.min(x))
  return x_norm

In [53]:
normalisation(temps)

array([0.  , 0.5 , 1.  , 0.25, 0.75])